name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - name: Build and push Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build . --platform linux/arm/v7,linux/arm/v8,linux/arm64,linux/amd64 -t ${{secrets.DOCKER_USER}}/nginx-proxy-pass:$GITHUB_SHA -t ${{secrets.DOCKER_USER}}/nginx-proxy-pass:latest --push
        echo "Docker push successfully"
        echo ${{secrets.DOCKER_USER}}/nginx-proxy-pass:$GITHUB_SHA
